spring.application.name=escalas
# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/escalas_basc
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuração do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# O 'update' cria ou atualiza as tabelas automaticamente no banco de dados baseado nas suas classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true